# Use Ubuntu as the base image
FROM ubuntu:latest

# Set the maintainer label
LABEL maintainer="pvlab373@outlook.com"

# Update the package list and install dependencies
RUN apt-get update && apt-get install -y \
    software-properties-common \
    build-essential \
    libssl-dev \
    libffi-dev \
    python3-dev \
    python3-pip \
    git \
    openssh-client \
    iputils-ping \
    curl \
    wget \
    unzip \
    net-tools \
    tcpdump \
    nmap \
    dnsutils \
    iproute2 \
    iperf3 \
    iftop \
    iptraf-ng \
    ethtool \
    mtr-tiny \
    jq \
    htop \
    nano

# Install Python 3.10
RUN add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install -y python3.10 python3.10-distutils

# Install Ansible core version 2.16
RUN pip3 install ansible-core==2.16.0

# Determine architecture and install Terraform version 1.6.6
ARG TARGETARCH
RUN if [ "$TARGETARCH" = "amd64" ]; then \
        wget https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip -O terraform.zip; \
    elif [ "$TARGETARCH" = "arm64" ]; then \
        wget https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_arm64.zip -O terraform.zip; \
    fi && \
    unzip terraform.zip -d /usr/local/bin/ && rm terraform.zip


# Install Ansible collections for Cisco IOS, Arista EOS, AVD, and Palo Alto PANOS
RUN ansible-galaxy collection install cisco.ios
RUN ansible-galaxy collection install arista.eos
RUN ansible-galaxy collection install arista.avd
RUN ansible-galaxy collection install paloaltonetworks.panos

# Set the locale environment variables
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

# Cleanup
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /terraform_1.6.6_linux_amd64.zip

# Set the working directory
WORKDIR /workspace

# Default command
CMD ["bash"]