name: Docker Image CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 0'
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Determine Tag for Build
      id: versioning
      run: |
        if [[ $GITHUB_EVENT_NAME == 'schedule' ]]; then
          git fetch --tags
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          IFS='.' read -ra VER <<< "${LATEST_TAG//v/}"
          MAJOR=${VER[0]}
          MINOR=${VER[1]}
          PATCH=${VER[2]}
          let PATCH+=1
          NEW_TAG="v${MAJOR}.${MINOR}.${PATCH}"
          echo "VERSION_TAG=$NEW_TAG" >> $GITHUB_ENV
        elif [[ $GITHUB_REF_TYPE == 'tag' ]]; then
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "VERSION_TAG=$TAG_NAME" >> $GITHUB_ENV
        else
          echo "VERSION_TAG=dev" >> $GITHUB_ENV
        fi

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
      tags: |
        pvlab373/autobox:${{ env.VERSION_TAG }}
        pvlab373/autobox:latest
      platforms: linux/amd64,linux/arm64